func sleep(int duration) {
    let startTime = clock();
    loop {
        if(clock() - startTime > duration)
            return;
        yield;
    }
}

func boring(string msg) chan(string) {
    let c = chan(string);
    task(chan(string) c, string msg) {
        int i = 0;
        loop {
            c <- (msg ~ " " ~ i);
            i ++;
            sleep(random(1000));
        }
    }(c, msg);
    return c;
}

main {
    let joe = boring("Joe");
    let ann = boring("Ann");
    loop(5) {
        print(<- joe);
        print(<- ann);
    }
    print("You're boring; I'm leaving.");
} 
