main {
    var a = true as var;
    print(a as int);
}

/*
Todo:
    - déclaration d'une variable locale et d'une fonction du même nom

    Suggestions:
    Système de channel comme mosaiq
    Variables globales
    Type Object (orienté prototype)
    Type Pointeur (type uniquement accessible dans les primitives)
    Multiples valeurs de retour: a, b = foo(); func() int, int {}
    Un système d'événement appelée extérieurement:
        event HelloWorld() { print("Hello World !"); }
*/