//


func foo() int {
    print("hey");
    return 3;
}


var b;
main {
    a();
    b = 5.2;
    print(b);
}


let a = &(func() int)foo;// 

/*
Todo:
    - déclaration d'une variable locale et d'une fonction du même nom

    Suggestions:
    Système de channel comme mosaiq
    Variables globales
    Type Object (orienté prototype)
    Multiples valeurs de retour: a, b = foo(); func() int, int {}
    Un système d'événement appelée extérieurement:
        event HelloWorld() { print("Hello World !"); }
    Constantes globales et enum
*/